//! HQC-1 C reference implementation.
//!
//! Generated by hand-run tooling from `src/ffi/mod.rs`; do not edit.
//! Symbols carry the `hqc1_` prefix applied by the build script's generated
//! prefix header, which is what lets all three variants coexist in one binary.
#![allow(dead_code)]

use super::{RmCodeword, RmExpandedCdw, Shake256IncCtx};

unsafe extern "C" {
    /// C: `hqc1_code_decode`
    #[link_name = "hqc1_code_decode"]
    pub fn code_decode(m: *mut u64, em: *const u64);

    /// C: `hqc1_code_encode`
    #[link_name = "hqc1_code_encode"]
    pub fn code_encode(em: *mut u64, m: *const u64);

    /// C: `hqc1_compute_elp`  // `static` in C; needs the un-static rewrite
    #[link_name = "hqc1_compute_elp"]
    pub fn compute_elp(sigma: *mut u16, syndromes: *const u16) -> u16;

    /// C: `hqc1_compute_error_values`  // `static` in C; needs the un-static rewrite
    #[link_name = "hqc1_compute_error_values"]
    pub fn compute_error_values(error_values: *mut u16, z: *const u16, error: *const u8);

    /// C: `hqc1_compute_fft_betas`  // `static` in C; needs the un-static rewrite
    #[link_name = "hqc1_compute_fft_betas"]
    pub fn compute_fft_betas(betas: *mut u16);

    /// C: `hqc1_compute_roots`  // `static` in C; needs the un-static rewrite
    #[link_name = "hqc1_compute_roots"]
    pub fn compute_roots(error: *mut u8, sigma: *mut u16);

    /// C: `hqc1_compute_subset_sums`  // `static` in C; needs the un-static rewrite
    #[link_name = "hqc1_compute_subset_sums"]
    pub fn compute_subset_sums(subset_sums: *mut u16, set: *const u16, set_size: u16);

    /// C: `hqc1_compute_syndromes`  // `static` in C; needs the un-static rewrite
    #[link_name = "hqc1_compute_syndromes"]
    pub fn compute_syndromes(syndromes: *mut u16, cdw: *mut u8);

    /// C: `hqc1_compute_z_poly`  // `static` in C; needs the un-static rewrite
    #[link_name = "hqc1_compute_z_poly"]
    pub fn compute_z_poly(z: *mut u16, sigma: *const u16, degree: u16, syndromes: *const u16);

    /// C: `hqc1_correct_errors`  // `static` in C; needs the un-static rewrite
    #[link_name = "hqc1_correct_errors"]
    pub fn correct_errors(cdw: *mut u8, error_values: *const u16);

    /// C: `hqc1_crypto_kem_dec`
    #[link_name = "hqc1_crypto_kem_dec"]
    pub fn crypto_kem_dec(k_prime: *mut u8, c_kem: *const u8, dk_kem: *const u8) -> i32;

    /// C: `hqc1_crypto_kem_enc`
    #[link_name = "hqc1_crypto_kem_enc"]
    pub fn crypto_kem_enc(c_kem: *mut u8, k: *mut u8, ek_kem: *const u8) -> i32;

    /// C: `hqc1_crypto_kem_keypair`
    #[link_name = "hqc1_crypto_kem_keypair"]
    pub fn crypto_kem_keypair(ek_kem: *mut u8, dk_kem: *mut u8) -> i32;

    /// C: `hqc1_encode`
    #[link_name = "hqc1_encode"]
    pub fn encode(word: *mut RmCodeword, message: i32);

    /// C: `hqc1_expand_and_sum`
    #[link_name = "hqc1_expand_and_sum"]
    pub fn expand_and_sum(dest: *mut RmExpandedCdw, src: *const RmCodeword);

    /// C: `hqc1_fft`
    #[link_name = "hqc1_fft"]
    pub fn fft(w: *mut u16, f: *const u16, f_coeffs: usize);

    /// C: `hqc1_fft_retrieve_error_poly`
    #[link_name = "hqc1_fft_retrieve_error_poly"]
    pub fn fft_retrieve_error_poly(error: *mut u8, w: *const u16);

    /// C: `hqc1_find_peaks`
    #[link_name = "hqc1_find_peaks"]
    pub fn find_peaks(transform: *mut RmExpandedCdw) -> i32;

    /// C: `hqc1_gf_carryless_mul`
    #[link_name = "hqc1_gf_carryless_mul"]
    pub fn gf_carryless_mul(c: *mut u8, a: u8, b: u8);

    /// C: `hqc1_gf_generate`
    #[link_name = "hqc1_gf_generate"]
    pub fn gf_generate(exp: *mut u16, log: *mut u16, m: i16);

    /// C: `hqc1_gf_inverse`
    #[link_name = "hqc1_gf_inverse"]
    pub fn gf_inverse(a: u16) -> u16;

    /// C: `hqc1_gf_mod_c`
    #[link_name = "hqc1_gf_mod_c"]
    pub fn gf_mod_c(i: u16, modulus: u16) -> u16;

    /// C: `hqc1_gf_mul`
    #[link_name = "hqc1_gf_mul"]
    pub fn gf_mul(a: u16, b: u16) -> u16;

    /// C: `hqc1_gf_reduce`  // `static` in C; needs the un-static rewrite
    #[link_name = "hqc1_gf_reduce"]
    pub fn gf_reduce(x: u16) -> u16;

    /// C: `hqc1_gf_square`
    #[link_name = "hqc1_gf_square"]
    pub fn gf_square(a: u16) -> u16;

    /// C: `hqc1_hadamard`
    #[link_name = "hqc1_hadamard"]
    pub fn hadamard(src: *mut RmExpandedCdw, dst: *mut RmExpandedCdw);

    /// C: `hqc1_hash_g`
    #[link_name = "hqc1_hash_g"]
    pub fn hash_g(output: *mut u8, hash_ek_kem: *const u8, m: *const u8, salt: *const u8);

    /// C: `hqc1_hash_h`
    #[link_name = "hqc1_hash_h"]
    pub fn hash_h(output: *mut u8, ek_kem: *const u8);

    /// C: `hqc1_hash_i`
    #[link_name = "hqc1_hash_i"]
    pub fn hash_i(output: *mut u8, seed: *const u8);

    /// C: `hqc1_hash_j`
    #[link_name = "hqc1_hash_j"]
    pub fn hash_j(output: *mut u8, hash_ek_kem: *const u8, sigma: *const u8, c_kem: *const u64,);

    /// C: `hqc1_hqc_c_kem_from_string`
    #[link_name = "hqc1_hqc_c_kem_from_string"]
    pub fn hqc_c_kem_from_string(c_pke: *mut u64, salt: *mut u8, ct: *const u8);

    /// C: `hqc1_hqc_c_kem_to_string`
    #[link_name = "hqc1_hqc_c_kem_to_string"]
    pub fn hqc_c_kem_to_string(ct: *mut u8, c_kem: *const u64);

    /// C: `hqc1_hqc_dk_pke_from_string`
    #[link_name = "hqc1_hqc_dk_pke_from_string"]
    pub fn hqc_dk_pke_from_string(y: *mut u64, dk_pke: *const u8);

    /// C: `hqc1_hqc_ek_pke_from_string`
    #[link_name = "hqc1_hqc_ek_pke_from_string"]
    pub fn hqc_ek_pke_from_string(h: *mut u64, s: *mut u64, ek_pke: *const u8);

    /// C: `hqc1_hqc_pke_decrypt`
    #[link_name = "hqc1_hqc_pke_decrypt"]
    pub fn hqc_pke_decrypt(m: *mut u64, dk_pke: *const u8, c_pke: *const u64);

    /// C: `hqc1_hqc_pke_encrypt`
    #[link_name = "hqc1_hqc_pke_encrypt"]
    pub fn hqc_pke_encrypt(c_pke: *mut u64, ek_pke: *const u8, m: *const u64, theta: *const u8,);

    /// C: `hqc1_hqc_pke_keygen`
    #[link_name = "hqc1_hqc_pke_keygen"]
    pub fn hqc_pke_keygen(ek_pke: *mut u8, dk_pke: *mut u8, seed: *mut u8);

    /// C: `hqc1_prng_init`
    #[link_name = "hqc1_prng_init"]
    pub fn prng_init(entropy_input: *mut u8, personalization_string: *mut u8, enlen: u32, perlen: u32);

    /// C: `hqc1_radix`  // `static` in C; needs the un-static rewrite
    #[link_name = "hqc1_radix"]
    pub fn radix(f0: *mut u16, f1: *mut u16, f: *const u16, m_f: u32);

    /// C: `hqc1_radix_big`  // `static` in C; needs the un-static rewrite
    #[link_name = "hqc1_radix_big"]
    pub fn radix_big(f0: *mut u16, f1: *mut u16, f: *const u16, m_f: u32);

    /// C: `hqc1_reed_muller_decode`
    #[link_name = "hqc1_reed_muller_decode"]
    pub fn reed_muller_decode(msg: *mut u64, cdw: *const u64);

    /// C: `hqc1_reed_muller_encode`
    #[link_name = "hqc1_reed_muller_encode"]
    pub fn reed_muller_encode(cdw: *mut u64, msg: *const u64);

    /// C: `hqc1_reed_solomon_decode`
    #[link_name = "hqc1_reed_solomon_decode"]
    pub fn reed_solomon_decode(msg: *mut u64, cdw: *mut u64);

    /// C: `hqc1_reed_solomon_encode`
    #[link_name = "hqc1_reed_solomon_encode"]
    pub fn reed_solomon_encode(cdw: *mut u64, msg: *const u64);

    /// C: `hqc1_schoolbook_mul`
    #[link_name = "hqc1_schoolbook_mul"]
    pub fn schoolbook_mul(r: *mut u64, a: *const u64, b: *const u64, n: usize);

    /// C: `hqc1_shake256_inc_squeeze`
    #[link_name = "hqc1_shake256_inc_squeeze"]
    pub fn shake256_inc_squeeze(output: *mut u8, output_size: u32, xof_ctx: *mut Shake256IncCtx);

    /// C: `hqc1_vect_add`
    #[link_name = "hqc1_vect_add"]
    pub fn vect_add(o: *mut u64, v1: *const u64, v2: *const u64, size: u32);

    /// C: `hqc1_vect_compare`
    #[link_name = "hqc1_vect_compare"]
    pub fn vect_compare(v1: *const u8, v2: *const u8, size: u32) -> u8;

    /// C: `hqc1_vect_generate_random_support1`
    #[link_name = "hqc1_vect_generate_random_support1"]
    pub fn vect_generate_random_support1(ctx: *mut Shake256IncCtx, support: *mut u32, weight: u16);

    /// C: `hqc1_vect_generate_random_support2`
    #[link_name = "hqc1_vect_generate_random_support2"]
    pub fn vect_generate_random_support2(ctx: *mut Shake256IncCtx, support: *mut u32, weight: u16);

    /// C: `hqc1_vect_mul`
    #[link_name = "hqc1_vect_mul"]
    pub fn vect_mul(o: *mut u64, a1: *const u64, a2: *const u64);

    /// C: `hqc1_vect_sample_fixed_weight1`
    #[link_name = "hqc1_vect_sample_fixed_weight1"]
    pub fn vect_sample_fixed_weight1(ctx: *mut Shake256IncCtx, v: *mut u64, weight: u16);

    /// C: `hqc1_vect_sample_fixed_weight2`
    #[link_name = "hqc1_vect_sample_fixed_weight2"]
    pub fn vect_sample_fixed_weight2(ctx: *mut Shake256IncCtx, v: *mut u64, weight: u16);

    /// C: `hqc1_vect_set_random`
    #[link_name = "hqc1_vect_set_random"]
    pub fn vect_set_random(ctx: *mut Shake256IncCtx, v: *mut u64);

    /// C: `hqc1_vect_truncate`
    #[link_name = "hqc1_vect_truncate"]
    pub fn vect_truncate(v: *mut u64);

    /// C: `hqc1_vect_write_support_to_vector`
    #[link_name = "hqc1_vect_write_support_to_vector"]
    pub fn vect_write_support_to_vector(v: *mut u64, support: *const u32, weight: u16);

    /// C: `hqc1_xof_get_bytes`
    #[link_name = "hqc1_xof_get_bytes"]
    pub fn xof_get_bytes(xof_ctx: *mut Shake256IncCtx, output: *mut u8, output_size: u32);

    /// C: `hqc1_xof_init`
    #[link_name = "hqc1_xof_init"]
    pub fn xof_init(xof_ctx: *mut Shake256IncCtx, seed: *const u8, seed_size: u32);

}